steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=$$GCP_CREDENTIALS
        gcloud config set project $$GCP_PROJECT_ID
        cd terraform
        terraform init
        terraform apply -auto-approve
substitutions:
  _GCP_CREDENTIALS: $$GCP_CREDENTIALS
  _GCP_PROJECT_ID: $$secrets.GCP_PROJECT_ID
