steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=${_GCP_CREDENTIALS}
        gcloud config set project ${_GCP_PROJECT_ID}
        cd terraform
        terraform init
        terraform apply -auto-approve

substitutions:
  _GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  _GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
