steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=krishtest-390320-55a2c26ed699.json
        gcloud config set project $PROJECT_ID
        gcloud components install terraform
        cd terraform
        terraform init
        terraform apply -auto-approve

substitutions:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}



        
