steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=var.credentials_file
        gcloud config set project var.project_id
        cd terraform
        gcloud components install terraform
        terraform init
        terraform apply -auto-approve
