steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=$$CREDENTIALS_FILE_PATH
        gcloud config set project $$PROJECT_ID
        cd terraform
        gcloud components install terraform
        terraform init
        terraform apply -auto-approve

substitutions:
  _CREDENTIALS_FILE_PATH: krishtest-390320-55a2c26ed699.json
  _PROJECT_ID: krishtest-390320



        
