# This is a basic workflow to help you get started with Actions

name: GCP cloud build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/checkout@v3
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: Authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Deploy with Terraform
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_CREDENTIALS }}
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          cd terraform
          terraform init
          terraform apply -auto-approve
          
      #- name: Configure Docker
       # run: |
       #   echo ${{ secrets.GCP_CREDENTIALS }} | base64 --decode > ${HOME}/gcloud.json
       #   gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
       #   gcloud auth configure-docker

     # - name: Build and push Docker image
     #   run: |
      #    docker build -t gcr.io/${{ secrets.GCP_BUILD_STAGING_TRIGGER_ID }}/sample-html-page:${{ github.sha }} .
       #   docker push gcr.io/${{ secrets.GCP_BUILD_STAGING_TRIGGER_ID }}/sample-html-page:${{ github.sha }}
     

      #- name: 'Use gcloud CLI'
       # run: 'gcloud info'
        
      # - name: Deploy to Cloud Run
       # run: |
        #  gcloud beta builds triggers run deploy sample-html-page \
         #   --image=gcr.io/${{ secrets.GCP_BUILD_STAGING_TRIGGER_ID }}/sample-html-page:${{ github.sha }} \
          #  --region=us-central1 \
          #  --platform=managed

      #- name: 'Start Google Cloud Build trigger'
       # run: |
        # export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        # gcloud beta builds triggers run ${{ secrets.GCP_BUILD_STAGING_TRIGGER_ID }} --tag=${{ github.event.release.tag_name }}


