name: GCP cloud build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: Authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
          
      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_CREDENTIALS }} | base64 --decode > ${HOME}/gcloud.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_BUILD_STAGING_TRIGGER_ID }}/sample-html-page:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_BUILD_STAGING_TRIGGER_ID }}/sample-html-page:${{ github.sha }}

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform changes
        run: |
          cd terraform
          terraform apply -auto-approve
